import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ChatLauncher } from "@/features/chatbot/components/ChatLauncher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* pb-28 reserves room for the fixed launcher so it never permanently
          covers content at the bottom of a scrolled page. It lives here rather
          than per-page because the launcher does. */}
      <body className="min-h-full flex flex-col pb-28">
        {children}
        {/* Mounted in the root layout, so the assistant is reachable from
            every route rather than only the landing page. */}
        <ChatLauncher />
      </body>
    </html>
  );
}
