import type { SupporterProfile } from "./types";

export const DEMO_SUPPORTER_PROFILE: SupporterProfile = {
  demoLabel: "Supporter profile",
  displayName: "Maya C.",
  initials: "MC",
  summary: [
    {
      id: "total-donated",
      label: "Total donated",
      value: "HK$3,600",
      helperText: "Across one-time and monthly support.",
    },
    {
      id: "donation-count",
      label: "Donations",
      value: "6",
      helperText: "Including recurring and one-time gifts.",
    },
    {
      id: "volunteer-hours",
      label: "Volunteer hours",
      value: "18",
      helperText: "Across community and event activities.",
    },
    {
      id: "milestones",
      label: "Milestones",
      value: "4",
      helperText: "Participation badges, not supporter rankings.",
    },
  ],
  donations: [
    {
      id: "donation-sports",
      programmeInterest: "Sports",
      amountHkd: 1500,
      contributionType: "monthly",
      note: "Supporter interest. This does not imply restricted allocation.",
    },
    {
      id: "donation-family",
      programmeInterest: "Family Support",
      amountHkd: 1000,
      contributionType: "one-time",
      note: "Supporter interest. This does not imply restricted allocation.",
    },
    {
      id: "donation-needed",
      programmeInterest: "Where Needed Most",
      amountHkd: 1100,
      contributionType: "one-time",
      note: "Supporter interest. This does not imply restricted allocation.",
    },
  ],
  contributionSummary: {
    oneTimeTotalHkd: 2100,
    monthlyTotalHkd: 1500,
    monthlyCount: 3,
  },
  volunteer: {
    totalHours: 18,
    activitiesAttended: 5,
    interests: ["Sports days", "Event support", "Community activities"],
  },
  communityRecognition: {
    period: "demo-2026",
    volunteerChampions: [
      {
        id: "volunteer-1",
        category: "volunteer",
        rank: 1,
        displayName: "Alex T.",
        isAnonymous: false,
        isCurrentProfile: false,
        volunteerHours: 42,
        activitiesAttended: 11,
        supportInterest: "Sports days",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "volunteer-2",
        category: "volunteer",
        rank: 2,
        displayName: "Jordan L.",
        isAnonymous: false,
        isCurrentProfile: false,
        volunteerHours: 36,
        activitiesAttended: 9,
        supportInterest: "Event support",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "volunteer-3",
        category: "volunteer",
        rank: 3,
        displayName: "Anonymous supporter",
        isAnonymous: true,
        isCurrentProfile: false,
        volunteerHours: 28,
        activitiesAttended: 8,
        supportInterest: "Community activities",
        visibilityStatus: "anonymous-demo",
        demoOnly: true,
      },
      {
        id: "volunteer-4",
        category: "volunteer",
        rank: 4,
        displayName: "Maya C.",
        isAnonymous: false,
        isCurrentProfile: true,
        volunteerHours: 18,
        activitiesAttended: 5,
        supportInterest: "Sports days",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "volunteer-5",
        category: "volunteer",
        rank: 5,
        displayName: "Sam W.",
        isAnonymous: false,
        isCurrentProfile: false,
        volunteerHours: 15,
        activitiesAttended: 4,
        supportInterest: "Event support",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
    ],
    givingSupporters: [
      {
        id: "giving-1",
        category: "giving",
        rank: 1,
        displayName: "Anonymous supporter",
        isAnonymous: true,
        isCurrentProfile: false,
        donationTotalHkd: 9600,
        contributionCount: 12,
        supportInterest: "Where Needed Most",
        visibilityStatus: "anonymous-demo",
        demoOnly: true,
      },
      {
        id: "giving-2",
        category: "giving",
        rank: 2,
        displayName: "Jordan L.",
        isAnonymous: false,
        isCurrentProfile: false,
        donationTotalHkd: 7200,
        contributionCount: 8,
        supportInterest: "Family Support",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "giving-3",
        category: "giving",
        rank: 3,
        displayName: "Priya K.",
        isAnonymous: false,
        isCurrentProfile: false,
        donationTotalHkd: 5400,
        contributionCount: 6,
        supportInterest: "Nutrition",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "giving-4",
        category: "giving",
        rank: 4,
        displayName: "Anonymous supporter",
        isAnonymous: true,
        isCurrentProfile: false,
        donationTotalHkd: 4800,
        contributionCount: 5,
        supportInterest: "Sports",
        visibilityStatus: "anonymous-demo",
        demoOnly: true,
      },
      {
        id: "giving-5",
        category: "giving",
        rank: 5,
        displayName: "Chris N.",
        isAnonymous: false,
        isCurrentProfile: false,
        donationTotalHkd: 4200,
        contributionCount: 7,
        supportInterest: "Employment and Life Skills",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
      {
        id: "giving-7",
        category: "giving",
        rank: 7,
        displayName: "Maya C.",
        isAnonymous: false,
        isCurrentProfile: true,
        donationTotalHkd: 3600,
        contributionCount: 6,
        supportInterest: "Sports",
        visibilityStatus: "public-demo",
        demoOnly: true,
      },
    ],
  },
  recentActivity: [
    {
      id: "activity-monthly",
      kind: "donation",
      title: "Monthly donation recorded",
      dateLabel: "12 Jun 2026",
      description: "HK$500 monthly contribution with Sports as the support interest.",
      demoOnly: true,
    },
    {
      id: "activity-volunteer",
      kind: "volunteer",
      title: "Volunteer activity attended",
      dateLabel: "28 May 2026",
      description: "Three volunteer hours recorded for a community activity.",
      demoOnly: true,
    },
    {
      id: "activity-one-time",
      kind: "donation",
      title: "One-time donation recorded",
      dateLabel: "4 Apr 2026",
      description: "HK$1,000 one-time contribution with Family Support as the interest.",
      demoOnly: true,
    },
  ],
  badges: [
    {
      id: "first-donation",
      label: "First Donation",
      description: "Recognises a first recorded donation journey.",
      tone: "support",
      demoOnly: true,
    },
    {
      id: "monthly-supporter",
      label: "Monthly Supporter",
      description: "Recognises setting up a monthly support preference.",
      tone: "support",
      demoOnly: true,
    },
    {
      id: "first-volunteer",
      label: "First Volunteer Activity",
      description: "Recognises taking part in a volunteer activity.",
      tone: "volunteer",
      demoOnly: true,
    },
    {
      id: "community-contributor",
      label: "Community Contributor",
      description: "Recognises participating in more than one kind of support.",
      tone: "community",
      demoOnly: true,
    },
  ],
  shareSummary:
    "Love 21 supporter impact: HK$3,600 donated, 18 volunteer hours, and 4 participation milestones. No private account details included.",
};
